# Generated by Django 5.1.5 on 2025-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('totalPrice', models.FloatField(default=0)),
            ],
        ),
    ]
