# Generated by Django 5.1.5 on 2025-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_selectedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
